### ISSUE TITLE
Website Cert Error

### ISSUE THREAD

**Issue by cody-todd22** [bepo13/destiny-stl-generator-web#11]
When trying to open the website on a chrome browser, I am met with NET::ERR_CERT_AUTHORITY_INVALID. Safari doesn't even attempt to open the site and states that it cannot find the server.

**Comment by bepo13** [comment]
I took the site down after receiving a cease and desist from Bungie, you can read the thread I made about it [here](https://www.reddit.com/r/DestinyTheGame/comments/17hpes0/shutting_down_destinystlgenerator_received_a/).

If you're looking for similar services there is a [Discord server](https://discord.gg/yPhFknrdU8) with resources.
